FROM node:14-alpine

# install dev pkg dependencies
RUN apk update && apk add \
    curl                ` # via dockerfile` \
    fish                ` # via fish` \
    make                ` # via makefile` \
    mlocate             ` # via dockerfile` \
    nano                ` # via dockerfile`

WORKDIR /app/src