version: "3.7"

services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        depends_on: []
        image: taskboard_backend
        ports:
        - 8000:8000
        volumes: []
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        depends_on: []
        image: taskboard_frontend
        ports:
        - 3000:3000
        volumes: []
    postgres:
        depends_on: []
        env_file:
        - ./env/postgres.env
        image: postgres:11.5
        ports:
        - 5432:5432
        volumes: []
volumes: {}
