version: "3.7"

services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        depends_on: []
        image: faid_backend
        ports:
        - 8000:8000
        volumes: []
    db:
        env_file:
        - ./env/postgres.env
        image: postgres:11.5
        ports:
        - 5432:5432
        volumes:
        - postgres_data:/var/lib/postgresql/data
