version: "3.7"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    command: sleep infinity
    depends_on: ["db"]
    env_file:
      - ./env/django.env
      - ./env/postgres.env
    image: faid_backend_dev
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app/src
      - $HOME/.config/pudb:/root/.config/pudb
      - /opt/taskboard/backend/fish_history:/root/.local/share/fish/fish_history
      - /opt/taskboard/backend/pytest_report.html:/app/pytest_report.html
      - /opt/taskboard/backend/assets:/app/assets
      - /opt/taskboard/backend/ipython:/root/.ipython
      - backend_site_packages:/usr/local/lib/python3.9/site-packages
      - backend_usr_local_bin:/usr/local/bin
  db:
    env_file:
      - ./env/postgres.env
    image: postgres:11.5
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  backend_site_packages: {}
  backend_usr_local_bin: {}
  postgres_data: {}
