FROM python:3

# update pip
RUN pip install --upgrade pip

# install dev pkg dependencies
RUN apt-get update && apt-get install -y \
    fish                ` # via :fish` \
    make                ` # via :makefile` \
    nano

# install dev pip dependencies
RUN pip install \
    isort               ` # via :isort` \
    pip-tools           ` # via :pip-compile`

# create a python venv that we can easily store inside a docker volume
RUN python3 -m venv /app/env
ENV PATH="/app/env/bin:${PATH}"

WORKDIR /app/src
