# Generated by Django 3.2 on 2021-04-16 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('changemaker_name', models.CharField(max_length=255, verbose_name='Name of the changemaker')),
                ('location', models.TextField(verbose_name='Location of the project')),
                ('date_of_birth', models.DateField(verbose_name='Birth date of the changemaker')),
                ('project_name', models.CharField(max_length=255, verbose_name='Name of the project')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description of project, or a link to a video')),
                ('is_approved', models.BooleanField(default=False, verbose_name='approved')),
                ('email', models.EmailField(max_length=254, verbose_name='Email where we can contact the changemaker')),
                ('google_doc_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='Contains additional onboarding information')),
                ('description_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='A video describing the project')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.task')),
            ],
            options={
                'permissions': (('can_reject_project_requests', 'Can reject project requests'), ('can_request_onboarding_calls_and_quiz_results', 'Can request onboarding calls and quiz results'), ('can_approve_project_requests', 'Can approve project requests')),
            },
        ),
    ]
