# Generated by Django 2.2.10 on 2020-04-29 18:06

from django.db import migrations
from django.contrib.auth.models import Group


def create_task_lists(apps, schema_editor):
    group = Group.objects.get(name="volunteer")
    TaskList = apps.get_model("tasks", "TaskList")
    TaskList.objects.create(
        name="Project Requests", slug="project-requests", group_id=group.id,
    )


# Generated by Django 2.2.10 on 2020-05-07 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
        ("users", "0002_create_groups"),
    ]

    operations = [
        migrations.RunPython(create_task_lists),
    ]
