# Generated by Django 2.2.10 on 2020-04-29 18:06

from django.db import migrations
from django.contrib.auth.models import Group


def create_groups(apps, schema_editor):
    Group.objects.create(name="changemaker")
    Group.objects.create(name="volunteer")
    Group.objects.create(name="frontlineaid_member")
    Group.objects.create(name="frontlineaid_admin")


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_groups),
    ]
